"""
Database CLI Commands

Commands for database management:
- reroute db init: Initialize migrations
- reroute db migrate: Create migration
- reroute db upgrade: Apply migrations
- reroute db downgrade: Rollback migrations
"""

import click
import sys
from pathlib import Path
from ..utils import progress_step, success_message, next_steps, handle_error, CLIError


@click.group()
def db():
    """Database management commands"""
    pass


@db.command()
def init():
    """
    Initialize database migrations

    Creates migrations directory and configuration files.
    """
    click.secho("\n" + "=" * 50, fg='cyan', bold=True)
    click.secho("Initializing Database Migrations", fg='cyan', bold=True)
    click.secho("=" * 50 + "\n", fg='cyan', bold=True)

    migrations_dir = Path("migrations")
    if migrations_dir.exists():
        raise CLIError(
            "Migrations directory already exists",
            suggestion="If you want to reinitialize, delete the 'migrations' directory first:\n"
                      "  rm -rf migrations alembic.ini",
            error_code="DB001"
        )

    try:
        with progress_step("Creating migrations directory"):
            migrations_dir.mkdir(exist_ok=True)
            (migrations_dir / "versions").mkdir(exist_ok=True)

        # Create alembic.ini
        alembic_ini_content = """# Alembic Migration Configuration
# Generated by REROUTE

[alembic]
script_location = migrations
prepend_sys_path = .
version_path_separator = os

[loggers]
keys = root,sqlalchemy,alembic

[handlers]
keys = console

[formatters]
keys = generic

[logger_root]
level = WARN
handlers = console

[logger_sqlalchemy]
level = WARN
handlers =
qualname = sqlalchemy.engine

[logger_alembic]
level = INFO
handlers =
qualname = alembic

[handler_console]
class = StreamHandler
args = (sys.stderr,)
level = NOTSET
formatter = generic

[formatter_generic]
format = %(levelname)-5.5s [%(name)s] %(message)s
datefmt = %H:%M:%S
"""
        with progress_step("Creating alembic.ini"):
            Path("alembic.ini").write_text(alembic_ini_content)

        # Create env.py
        env_py_content = """from logging.config import fileConfig
from sqlalchemy import engine_from_config, pool
from alembic import context
import os
import sys

# Add project root to path
sys.path.insert(0, os.path.dirname(os.path.dirname(__file__)))

# Import your models here
from reroute.db.models import Base
# from app.models import *  # Import all your models

# Alembic Config object
config = context.config

# Interpret the config file for Python logging
if config.config_file_name is not None:
    fileConfig(config.config_file_name)

# Set target metadata
target_metadata = Base.metadata

# Get database URL from environment
database_url = os.getenv('REROUTE_DATABASE_URL', 'sqlite:///./app.db')
config.set_main_option('sqlalchemy.url', database_url)


def run_migrations_online():
    connectable = engine_from_config(
        config.get_section(config.config_ini_section),
        prefix='sqlalchemy.',
        poolclass=pool.NullPool,
    )

    with connectable.connect() as connection:
        context.configure(connection=connection, target_metadata=target_metadata)

        with context.begin_transaction():
            context.run_migrations()


if context.is_offline_mode():
    raise RuntimeError("Offline mode not supported")
else:
    run_migrations_online()
"""
        with progress_step("Creating migrations/env.py"):
            (migrations_dir / "env.py").write_text(env_py_content)

        # Success message with details
        success_message("Migrations initialized successfully!", {
            "Migrations Dir": "migrations/",
            "Config File": "alembic.ini"
        })

        next_steps([
            "reroute db migrate -m 'Initial migration'",
            "reroute db upgrade"
        ])

    except CLIError:
        raise  # Re-raise CLI errors to be handled by caller
    except Exception as e:
        handle_error(e, context="Database initialization")
        sys.exit(1)


@db.command()
@click.option('-m', '--message', required=True, help='Migration message')
def migrate(message):
    """
    Create a new migration

    Example:
        reroute db migrate -m "Add users table"
    """
    click.secho("\n" + "=" * 50, fg='cyan', bold=True)
    click.secho("Creating Database Migration", fg='cyan', bold=True)
    click.secho("=" * 50 + "\n", fg='cyan', bold=True)

    # Check if alembic is installed
    try:
        import alembic  # noqa: F401
    except ImportError:
        raise CLIError(
            "Alembic is not installed",
            suggestion="Install with: pip install alembic",
            error_code="DB010"
        )

    # Check if migrations are initialized
    if not Path("migrations").exists():
        raise CLIError(
            "Migrations not initialized",
            suggestion="Run 'reroute db init' first to initialize migrations.",
            error_code="DB011"
        )

    try:
        import subprocess

        click.secho(f"  Migration: ", fg='blue', nl=False)
        click.secho(message, fg='cyan', bold=True)
        click.echo()

        with progress_step("Generating migration"):
            result = subprocess.run(
                ['alembic', 'revision', '--autogenerate', '-m', message],
                capture_output=True,
                text=True
            )

        if result.returncode == 0:
            success_message("Migration created successfully!")
            if result.stdout:
                click.echo(result.stdout)

            next_steps(["reroute db upgrade"])
        else:
            raise CLIError(
                "Error creating migration",
                suggestion=result.stderr.strip() if result.stderr else "Check your database configuration and models.",
                error_code="DB012"
            )

    except CLIError:
        raise
    except Exception as e:
        handle_error(e, context="Migration creation")
        sys.exit(1)


@db.command()
def upgrade():
    """
    Apply all pending migrations

    Applies migrations to the database.
    """
    click.secho("\n" + "=" * 50, fg='cyan', bold=True)
    click.secho("Applying Database Migrations", fg='cyan', bold=True)
    click.secho("=" * 50 + "\n", fg='cyan', bold=True)

    # Check if migrations are initialized
    if not Path("migrations").exists():
        raise CLIError(
            "Migrations not initialized",
            suggestion="Run 'reroute db init' first to initialize migrations.",
            error_code="DB011"
        )

    try:
        import subprocess

        with progress_step("Applying migrations to database"):
            result = subprocess.run(
                ['alembic', 'upgrade', 'head'],
                capture_output=True,
                text=True
            )

        if result.returncode == 0:
            success_message("Migrations applied successfully!")
            if result.stdout:
                click.echo(result.stdout)
        else:
            raise CLIError(
                "Error applying migrations",
                suggestion=result.stderr.strip() if result.stderr else "Check your database connection and migration files.",
                error_code="DB020"
            )

    except CLIError:
        raise
    except Exception as e:
        handle_error(e, context="Migration upgrade")
        sys.exit(1)


@db.command()
@click.option('--steps', default=1, help='Number of migrations to rollback')
def downgrade(steps):
    """
    Rollback migrations

    Example:
        reroute db downgrade --steps 1
    """
    click.secho("\n" + "=" * 50, fg='yellow', bold=True)
    click.secho("Rolling Back Database Migrations", fg='yellow', bold=True)
    click.secho("=" * 50 + "\n", fg='yellow', bold=True)

    # Security: Validate steps parameter to prevent command injection
    try:
        steps_int = int(steps)
        if steps_int < 1:
            click.secho("\n[ERROR] Steps must be a positive integer (>= 1)", fg='red', bold=True)
            click.secho("\n[TIP] Example: reroute db downgrade --steps 1", fg='yellow')
            sys.exit(1)
        if steps_int > 100:
            click.secho("\n[ERROR] Steps cannot exceed 100 for safety", fg='red', bold=True)
            click.secho("\n[TIP] If you need to rollback more, do it in batches.", fg='yellow')
            sys.exit(1)
    except ValueError:
        click.secho(f"\n[ERROR] Invalid steps value: '{steps}'", fg='red', bold=True)
        click.secho("\n[TIP] Steps must be a positive integer. Example: --steps 1", fg='yellow')
        sys.exit(1)

    # Check if migrations are initialized
    if not Path("migrations").exists():
        raise CLIError(
            "Migrations not initialized",
            suggestion="Run 'reroute db init' first to initialize migrations.",
            error_code="DB011"
        )

    # Warn about destructive action
    click.secho(f"[WARNING] This will rollback {steps_int} migration(s).", fg='yellow')
    click.secho("          This action may result in data loss!", fg='yellow')
    if not click.confirm("\nAre you sure you want to proceed?", default=False):
        click.secho("\n[CANCELLED] Rollback cancelled by user.\n", fg='yellow')
        return

    try:
        import subprocess

        with progress_step(f"Rolling back {steps_int} migration(s)"):
            result = subprocess.run(
                ['alembic', 'downgrade', f'-{steps_int}'],
                capture_output=True,
                text=True
            )

        if result.returncode == 0:
            success_message("Rollback completed!")
            if result.stdout:
                click.echo(result.stdout)
        else:
            raise CLIError(
                "Error during rollback",
                suggestion=result.stderr.strip() if result.stderr else "Check migration history with 'reroute db history'.",
                error_code="DB033"
            )

    except CLIError:
        raise
    except Exception as e:
        handle_error(e, context="Migration rollback")
        sys.exit(1)


@db.command()
def current():
    """Show current migration version"""
    # Check if migrations are initialized
    if not Path("migrations").exists():
        raise CLIError(
            "Migrations not initialized",
            suggestion="Run 'reroute db init' first to initialize migrations.",
            error_code="DB011"
        )

    try:
        import subprocess

        result = subprocess.run(
            ['alembic', 'current'],
            capture_output=True,
            text=True
        )

        if result.returncode == 0:
            click.secho("\n[CURRENT] Current migration version:", fg='cyan', bold=True)
            if result.stdout.strip():
                click.echo(result.stdout)
            else:
                click.secho("  No migrations applied yet.", fg='yellow')
        else:
            raise CLIError(
                "Error getting current migration",
                suggestion=result.stderr.strip() if result.stderr else "Check your alembic configuration.",
                error_code="DB040"
            )

    except CLIError:
        raise
    except Exception as e:
        handle_error(e, context="Getting current migration")


@db.command()
def history():
    """Show migration history"""
    # Check if migrations are initialized
    if not Path("migrations").exists():
        raise CLIError(
            "Migrations not initialized",
            suggestion="Run 'reroute db init' first to initialize migrations.",
            error_code="DB011"
        )

    try:
        import subprocess

        result = subprocess.run(
            ['alembic', 'history'],
            capture_output=True,
            text=True
        )

        if result.returncode == 0:
            click.secho("\n[HISTORY] Migration history:", fg='cyan', bold=True)
            if result.stdout.strip():
                click.echo(result.stdout)
            else:
                click.secho("  No migrations found.", fg='yellow')
                click.secho("\n[TIP] Create a migration with: reroute db migrate -m 'Initial'", fg='blue')
        else:
            raise CLIError(
                "Error getting migration history",
                suggestion=result.stderr.strip() if result.stderr else "Check your alembic configuration.",
                error_code="DB041"
            )

    except CLIError:
        raise
    except Exception as e:
        handle_error(e, context="Getting migration history")
